version: '3.1'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
      - ./idf_test_mysql:/var/lib/mysql
    env_file:
      - .env
    environment:
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 20s
            retries: 10
    networks:
      - metanet1
    ports:
      - "3306:3306"
  
  # metabase:
  #   image: metabase/metabase:latest
  #   container_name: metabase
  #   hostname: metabase
  #   volumes:
  #   - /dev/urandom:/dev/random:ro
  #   ports:
  #     - 3000:3000
  #   networks:
  #     - metanet1
  #   depends_on:
  #     db:
  #       condition: service_healthy
  
  streamlit-dashboard:
    build: .
    command: streamlit run sales_by_month.py
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./solution/dashboard:/usr/src/app
    env_file:
      - .env
    ports:
      - 8501:8501

networks:
  metanet1:
    driver: bridge
volumes:
  idf_test_mysql:
